version: "3"

services:
  
  rameses-notification-server:
    image: "ramesesinc/notification-server:1.0"
    container_name: rameses-notification-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m

    ports: 
      - "7080:8080"


  download-server:
    image: nginx:latest
    container_name: download-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m

    environment:
      TZ: "Asia/Manila"

    ports:
      - "80:80"

    volumes:
      - ./download/conf.d:/etc/nginx/conf.d
      - ./download/resources:/resources


  etracs25-server:
    image: ramesesinc/etracs25-server-municipality:255.01.007
    container_name: etracs25-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m

    env_file:
      - ./env.conf

    ports:
      - "8060:8060"
      - "8061:8061"
      - "8070:8070"
      - "8080:8080"

    volumes:
      - ./etracs25/connections:/apps/server/workspace/services/apps/etracs25/connections/ext
      - ./etracs25/modules:/apps/server/workspace/services/apps/etracs25/modules
      - ./etracs25/raaf_report.sql:/apps/server/workspace/services/modules/etracs/rameses-gov-treasury-report-services.jar/sql/raaf_report.sql

      - ./etracs25/dev_modules/rptis:/rptis
      - ./etracs25/dev_modules/rptis/etracs_rptis.conf:/apps/server/workspace/services/apps/etracs25/modules.conf.d/etracs_rptis.conf
